name: Build APK with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build APK in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd \
        kivy/buildozer:latest \
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: birkarta-docker-apk
        path: bin/*.apk
        
    - name: Upload logs if failed
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: buildozer-logs
        path: .buildozer/logs/
